version: '3.8'

services:
  db:
    image: mysql:oraclelinux9
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_DATABASE: my_db
      MYSQL_PASSWORD: admin12345
      MYSQL_USER: test
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql


  rest-api:
    build: .
    container_name: rest-api
    restart: always
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/my_db
      spring.datasource.username: test
      spring.datasource.password: admin12345      
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  mysql-data:
    external: true

