version: '3.8'

services:
  db:
    image: mysql:oraclelinux9
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql


  rest-api:
    build: .
    container_name: rest-api
    restart: always
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/${DB_NAME}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}      
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  mysql-data:
    external: true

