apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: app-storageclass
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard

