apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tools-app
  template:
    metadata:
      labels:
        app: tools-app
    spec:
      containers:
        - name: tools-application
          image: kozijakinfo/tools-api:2.0
          ports:
          - containerPort: 8080
          env:
          - name: DB_URL
            value: mysql.default.svc.cluster.local
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: my-config-map
                key: db_name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: tools-app-service
spec:
  selector:
    app: tools-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
