apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools-app-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tools-app
  template:
    metadata:
      labels:
        app: tools-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 500
        runAsGroup: 501
        fsGroup: 500
      containers:
        - name: tools-application
          image: kozijakinfo/tools-api:4.0
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/health"
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            httpGet:
              path: "/health"
              port: 8080
          resources:
            requests:
              memory: 300Mi
              cpu: 400m
            limits:
              memory: 600Mi
              cpu: 800m
          env:
          - name: DB_URL
            value: mysql.default.svc.cluster.local
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: my-config-map
                key: db_name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: tools-app-service
spec:
  selector:
    app: tools-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
